modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Thutmose/Thut/issues"
license="All rights reserved"

[[mods]]
    modId="thutperms"
    version="${file.jarVersion}"
    displayName="Thut Permissions"
    authors="Thutmose"
    description='''
    Permissions mod for Forge
    '''
    
[[dependencies.thutessentials]]
    modId="minecraft"
    mandatory=true
    versionRange="version_mc"
    ordering="NONE"
    side="BOTH"